### ISSUE TITLE
Discover not updating the widget

### ISSUE THREAD

**Issue by edwardp3** [k-donn/plasmoid-wunderground#61]
Is there any reason why Discover6 does not automatically update the widget? I've been removing the widget from the panel, then deleting it in ~/.local/share/plasma/plasmoids to remove it, then download the update each time.

**Comment by k-donn** [comment]
Sorry for the delay! 

I cannot seem to find anything broken with the packaging of the widget. More versions should be coming out soon so I will see how Discover handles that.

**Comment by k-donn** [comment]
I suspect Discover might have had problems with newer versions of the widget being lower in number than the old Plasma 5 versions of the widget. The new release has a higher version so hopefully that fixes the problem.

**Comment by edwardp3** [comment]
I saw a new version of the widget was on the KDE store web site. 

Discover did not update the widget from the original 3.0.0, had to remove from the panel, download new widgets , select and reinstall, in order to get the current version 3.1.3.

**Comment by k-donn** [comment]
Strange. New changes will be pushed out this week, and I will mess with some more settings to try and force it to update.

**Comment by k-donn** [comment]
I pushed out 3.2.0. I also corrected the name of the license in the widget metadata. So look for GPL-2.0-or-later to show up for the license instead of "Unknown" which it shows up for me now.

**Comment by edwardp3** [comment]
Discover is still not seeing it. Installed 3.2.1 using the same procedures as outlined above.
